version: '3'
services:
  nginx:
    image: '${PRIMERO_IMAGE_REPOSITORY:-primeroims}/nginx:${PRIMERO_TAG:-latest}'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - selfsigned_certs:/certs
      - public:/srv/primero/application/public
    env_file:
      - docker/defaults.env
      - docker/local.env
    environment:
      - USE_LETS_ENCRYPT=false
    depends_on:
      - application
  application:
    env_file:
      - docker/defaults.env
      - docker/local.env
    ports:
      - "3000:3000"
  solr:
    env_file:
      - docker/defaults.env
      - docker/local.env
    ports:
      - "8983:8983"
  worker:
    env_file:
      - docker/defaults.env
      - docker/local.env
  postgres:
    env_file:
      - docker/defaults.env
      - docker/local.env
    ports:
      - "5432:5432"
