development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    pid_dir: tmp/pids
    path: /solr/primero
  auto_index_callback: after_commit
  auto_remove_callback: after_commit

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: OFF
    pid_dir: tmp/pids
    path: /solr/primero-test
  auto_index_callback: after_commit
  auto_remove_callback: after_commit
