---
- name: 'create the /srv/primero/external-certs directory'
  file:
    path: '/srv/primero/external-certs'
    state: 'directory'
  become: yes
  tags:
  - 'external-certs'

- name: 'Copy ssl key to remote host'
  copy:
    dest: '/srv/primero/external-certs/primero.key'
    mode: 'u=rw,go=r'
    content: '{{ nginx_ssl_key }}'
  become: yes
  when: nginx_ssl_key is defined
  tags:
  - 'external-certs'

- name: 'Copy ssl cert to remote host'
  copy:
    dest: '/srv/primero/external-certs/primero.crt'
    mode: 'u=rw,go=r'
    content: '{{ nginx_ssl_cert }}'
  become: yes
  when: nginx_ssl_cert is defined
  tags:
  - 'external-certs'
